# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {  { site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: OpenLore
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
# theme: minima
plugins:
  - jekyll-feed

# Collections
collections_dir: content
collections:
  info:
    output: true
    permalink: /info/:path/
  posts:
    output: true
    permalink: /:categories/:title/
  category:
    output: true
# Nav global
nav:
  frontier2424:
    title: Frontier2424
    url: /frontier2424/
    categories:
      characters:
        title: Characters
        url: /frontier2424/characters/
      factions:
        title: Factions
        url: /frontier2424/factions/
      locations:
        title: Locations
        url: /frontier2424/locations/
      events:
        title: Events
        url: /frontier2424/events/
      technology:
        title: Technology
        url: /frontier2424/technology/
      style-guides:
        title: Style guides
        url: /frontier2424/style-guides/
      stories:
        title: Stories
        url: /frontier2424/stories/
        hidden: true
  blackfire4:
    title: Blackfire 4
    url: /blackfire4/
    categories:
      locations:
        title: Locations
        url: /blackfire4/locations/
      organisations:
        title: Organisations
        url: /blackfire4/organisations/
      style-guides:
        title: Style guides
        url: /blackfire4/style-guides/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
